export const courses = [
    {
        id: 1,
        title: "Commercial & General Cook Training",
        category: "Culinary Arts",
        badge: "Most Popular Overseas",
        badgeColor: "bg-orange-500",
        duration: "45 – 90 Days Track",
        certification: "CTEVT Certified",
        description:
            "Master Continental, Pan-Asian, and authentic Nepali cuisines. Knife dynamics, food safety (HACCP), and high-volume commercial kitchen workflow.",
        tags: ["Continental", "Pan-Asian", "HACCP Certified", "Buffet Prep"],
        image: "/images/courses/culinary.jpg",
    },
    {
        id: 2,
        title: "Professional Bakery & Pastry Arts",
        category: "Baking Sciences",
        badge: "High Demand",
        badgeColor: "bg-blue-500",
        duration: "1 to 3 Months",
        certification: "CTEVT Level-1 & 2",
        description:
            "Artisan sourdoughs, French viennoiserie, wedding cake sculpting, sugar paste artistry, and commercial deck oven operations.",
        tags: ["Artisan Breads", "Pastry Decors", "Cost Calculation"],
        image: "/images/courses/bakery.jpg",
    },
    {
        id: 3,
        title: "Barista & Specialty Coffee Mastery",
        category: "Specialty Beverage",
        badge: "Fast Track Career",
        badgeColor: "bg-emerald-500",
        duration: "3 Weeks Intensive",
        certification: "SCA Aligned",
        description:
            "Extraction dialing, microfoam milk steaming, multi-pattern latte art (Rosetta, Swan), manual brewing (V60, Chemex, Aeropress), and café station management.",
        tags: ["Latte Art", "Dial-in Roasts", "Machine Tech"],
        image: "/images/courses/barista.jpg",
    },
    {
        id: 4,
        title: "Housekeeping & Front Office Operations",
        category: "Hotel Operations",
        badge: "Five-Star Standard",
        badgeColor: "bg-purple-500",
        duration: "2 Months",
        certification: "CTEVT Endorsed",
        description:
            "Five-star luxury room inspection protocols, chemical handling & linen care, customer service etiquette, and PMS (Property Management Software) navigation.",
        tags: ["Room Auditing", "Opera PMS", "Concierge Skills"],
        image: "/images/courses/hotel.jpg",
    },
    {
        id: 5,
        title: "Bartending, Mixology & Beverage Service",
        category: "Beverage Craft",
        badge: "Cruise Line Special",
        badgeColor: "bg-rose-500",
        duration: "35 Days",
        certification: "Industry Recognized",
        description:
            "Classic and modern mocktails, mixology chemistry, working flair, speed-pour techniques, bar cellar control, and guest behavior psychology for cruise liners.",
        tags: ["Classic Cocktails", "Speed Pouring", "Flair Acrobatics"],
        image: "/images/courses/bartender.jpg",
    },
    {
        id: 6,
        title: "Certified Caregiver & Healthcare Assistant",
        category: "Healthcare Services",
        badge: "Japan & UK Target",
        badgeColor: "bg-cyan-500",
        duration: "3 Months",
        certification: "SSW / Overseas Valid",
        description:
            "Geriatric support, vital sign tracking, first-aid CPR certification, wheelchair ergonomics, and specific visa interview training for Japan (SSW) and Europe.",
        tags: ["BLS / CPR", "Elder Care", "Japan SSW Prep"],
        image: "/images/courses/healthcare.jpg",
    },
];
